# Generated by Django 4.1.3 on 2022-11-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_details',
            fields=[
                ('cl', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roll_num', models.IntegerField()),
                ('branch', models.CharField(max_length=10)),
                ('Persent', models.BooleanField(default=True)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_api.class_details')),
            ],
        ),
    ]
