# Generated by Django 4.1.3 on 2022-11-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='Persent',
            new_name='Present',
        ),
        migrations.AlterField(
            model_name='student_details',
            name='branch',
            field=models.CharField(choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('ME', 'ME')], max_length=10),
        ),
    ]
