# Generated by Django 4.1.3 on 2023-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_api', '0003_student_details_finger_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='block_student',
            field=models.BooleanField(default=False),
        ),
    ]
